server:
  port: 8081
  servlet:
    # 项目的路径，配置如下之后，它的路径为http:locahost:8081/student
    context-path: /student
#    数据库
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/studentdata
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


debug: true